### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by ryaan-anthony** [workarea-commerce/workarea-emarsys#6]
response.body is coming back nil and we are getting this error:
```
NoMethodError: undefined method `[]' for nil:NilClass
  from workarea/emarsys/save_user.rb:22:in `perform'
```

**Comment by jyucis** [comment]
Please send me your emarsys configuration via keybase to user jyucis

The call to save_user is failing and then attempting to save the user record.

**Comment by GesJeremie** [comment]
@jyucis I worked on the same build than @ryaan-anthony, basically the credentials were wrong in the first place and therefore triggered that error -- Your answer helped me figured it out, **thanks**!

I think it's safe to say we can close the issue.

**Comment by bencrouse** [comment]
Thanks @GesJeremie, I'm closing this issue.
